# Generated by Django 6.0.6 on 2026-07-04 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agent", "0002_initial"),
        ("admin", "0001_initial"),
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="client.cliente",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="admin.order",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="admin.order",
            ),
        ),
        migrations.AddField(
            model_name="pointofinterest",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                help_text="Agar shartnoma qilingan bo'lsa, mos mijoz yozuvi",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="points_of_interest",
                to="client.cliente",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="admin.product",
            ),
        ),
        migrations.AddField(
            model_name="salary",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salaries",
                to="agent.agent",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visits",
                to="agent.agent",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visits",
                to="admin.pointofinterest",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salary",
            unique_together={("agent", "month")},
        ),
    ]
