# Generated by Django 6.0.6 on 2026-10-06 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
        ('apps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('firma_name', models.CharField(blank=True, max_length=120)),
                ('alternative_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='agent.agent')),
                ('user', models.OneToOneField(blank=True, help_text='Mijozning login hisobi (agar mijoz panelidan foydalansa)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
            },
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', "Yangi so'rov"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Mijozning izohi')),
                ('admin_note', models.TextField(blank=True, help_text='Admin izohi (masalan rad etish sababi)')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_reviewed', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to='client.cliente')),
                ('order', models.ForeignKey(blank=True, help_text='Tasdiqlangandan keyin yaratilgan nakladnoy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='apps.order')),
            ],
            options={
                'verbose_name': "Buyurtma so'rovi",
                'verbose_name_plural': "Buyurtma so'rovlari",
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='OrderRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.IntegerField(help_text="So'rov paytidagi narx")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='apps.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='client.orderrequest')),
            ],
            options={
                'verbose_name': "So'rov tovari",
                'verbose_name_plural': "So'rov tovarlari",
            },
        ),
    ]
