# Generated by Django 6.0.6 on 2026-10-06 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=3.0, help_text='Foiz stavkasi, masalan 3.5', max_digits=5)),
                ('balance_limit', models.IntegerField(default=0, help_text="Agentga berilishi mumkin bo'lgan maksimal naqd pul")),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agentlar',
            },
        ),
        migrations.CreateModel(
            name='AgentBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('given_amount', models.IntegerField(default=0)),
                ('returned_amount', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Agent balansi',
                'verbose_name_plural': 'Agent balanslari',
                'ordering': ['-date'],
            },
        ),
    ]
