# Generated by Django 6.0.6 on 2026-10-06 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliver_price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('competition_photo', models.ImageField(upload_to='cpashop/admin/')),
                ('start', models.DateField()),
                ('finish', models.DateField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'CPA sozlamalari',
                'verbose_name_plural': 'CPA sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('icon', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CpaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('operator', 'Operator'), ('deliver', 'Deliver')], default='user', max_length=10)),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cpashop.district')),
            ],
            options={
                'verbose_name': 'CPA foydalanuvchi',
                'verbose_name_plural': 'CPA foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('review', 'Review'), ('completed', 'Completed'), ('cancel', 'Cancel')], default='review', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('check_payment', models.ImageField(blank=True, null=True, upload_to='cpashop/payments/check/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cpashop.cpauser')),
            ],
            options={
                'verbose_name': 'Pul yechish (CPA)',
                'verbose_name_plural': 'Pul yechishlar (CPA)',
                'ordering': ['-payment_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='cpashop/products/')),
                ('sell_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('sale', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('telegram_url', models.CharField(blank=True, max_length=50, null=True)),
                ('discount', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpashop.category')),
            ],
            options={
                'verbose_name': 'Mahsulot (CPA)',
                'verbose_name_plural': 'Mahsulotlar (CPA)',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpashop.region'),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit_count', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpashop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpashop.cpauser')),
            ],
            options={
                'verbose_name': 'Ulashish linki',
                'verbose_name_plural': 'Ulashish linklari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('ready_to_order', 'Ready To Order'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('archived', 'Archived'), ('not_pick_up', 'Not Pick Up')], default='new', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_operator', models.TextField(blank=True, null=True)),
                ('send_date', models.DateTimeField(blank=True, null=True)),
                ('deliver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliver_orders', to='cpashop.cpauser')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cpashop.district')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_orders', to='cpashop.cpauser')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cpashop.cpauser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cpashop.product')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cpashop.thread')),
            ],
            options={
                'verbose_name': 'Buyurtma (CPA)',
                'verbose_name_plural': 'Buyurtmalar (CPA)',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpashop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpashop.cpauser')),
            ],
            options={
                'verbose_name': 'Sevimli',
                'verbose_name_plural': 'Sevimlilar',
            },
        ),
    ]
