# Generated by Django 6.0.6 on 2026-07-04 10:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agent", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price",
                    models.IntegerField(
                        help_text="Sotish paytidagi narx (o'zgarmasligi uchun saqlanadi)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Nakladnoy satri",
                "verbose_name_plural": "Nakladnoy satrlari",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "method",
                    models.CharField(
                        choices=[("cash", "Naqd"), ("bank", "Bank o'tkazmasi")],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        help_text="Bank to'lovi skrinshotini yuklash",
                        null=True,
                        upload_to="payments/",
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(default=False, help_text="Admin tasdiqladi"),
                ),
                ("note", models.TextField(blank=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "To'lov",
                "verbose_name_plural": "To'lovlar",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="PointOfInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Masalan: 'Quvonchli AZS-4'", max_length=255
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("azs", "AZS (yoqilg'i shaxobchasi)"),
                            ("avto_dukon", "Avto-do'kon"),
                        ],
                        default="azs",
                        max_length=20,
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Nuqta (AZS/Do'kon)",
                "verbose_name_plural": "Nuqtalar (AZS/Do'konlar)",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "sku",
                    models.CharField(
                        help_text="Tovar kodi, masalan: YG-001",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("description", models.TextField(blank=True)),
                ("price", models.IntegerField(default=0, help_text="So'mda narx")),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, help_text="Skladda mavjud miqdor"
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Shu miqdordan kam bo'lsa ogohlantirish chiqadi",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tovar",
                "verbose_name_plural": "Tovarlar",
            },
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(help_text="Oy boshi sanasi, masalan: 2026-06-01"),
                ),
                (
                    "total_sales",
                    models.IntegerField(
                        default=0, help_text="O'sha oyda jami sotilgan summa"
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "commission_amount",
                    models.IntegerField(
                        default=0, help_text="Foiz bo'yicha hisoblangan summa"
                    ),
                ),
                ("bonus", models.IntegerField(default=0)),
                (
                    "total_salary",
                    models.IntegerField(
                        default=0, help_text="commission_amount + bonus"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("calculated", "Hisoblandi"), ("paid", "To'landi")],
                        default="calculated",
                        max_length=20,
                    ),
                ),
                ("date_paid", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Maosh",
                "verbose_name_plural": "Maoshlar",
                "ordering": ["-month"],
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, help_text="Agent tashrif paytidagi GPS", null=True
                    ),
                ),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("telegram_sent", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tashrif",
                "verbose_name_plural": "Tashriflar",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this apps site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=20, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("paid", "To'langan"),
                            ("debt", "Qarz"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("cash", "Naqd"),
                            ("transfer", "Perechesleniye"),
                            ("debt", "Qarz (keyinroq)"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("total_sum", models.IntegerField(default=0)),
                (
                    "nak_picture",
                    models.ImageField(blank=True, null=True, upload_to="orders/"),
                ),
                ("note", models.TextField(blank=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="agent.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nakladnoy",
                "verbose_name_plural": "Nakladnoylar",
                "ordering": ["-date_created"],
            },
        ),
    ]
