# Generated by Django 6.0.6 on 2026-10-06 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0002_initial'),
        ('apps', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='client.cliente'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='apps.order'),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='apps.order'),
        ),
        migrations.AddField(
            model_name='orderreturnitem',
            name='order_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='apps.orderreturn'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='apps.order'),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text="Agar shartnoma qilingan bo'lsa, mos mijoz yozuvi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_of_interest', to='client.cliente'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='apps.category'),
        ),
        migrations.AddField(
            model_name='orderreturnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='apps.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='apps.product'),
        ),
        migrations.AddField(
            model_name='salary',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='agent.agent'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='order',
            field=models.ForeignKey(blank=True, help_text="Agar shu nakladnoy sababli bo'lsa", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='apps.order'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='apps.product'),
        ),
        migrations.AddField(
            model_name='visit',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='agent.agent'),
        ),
        migrations.AddField(
            model_name='visit',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='apps.pointofinterest'),
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together={('agent', 'month')},
        ),
    ]
